### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by larsbutler** [swiftstack/vagrant-swift-all-in-one#12]
Hi there,

Is there a plan to add a open source license to these scripts? I'm sure people would love to be able to use/build on this stuff in some open source projects (myself included!), but without a license we cannot.

Relevant: https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

Thanks!

**Comment by clayg** [comment]
Oh sure, seems reasonable - I'll ask about and see what folks wanna use.  Thanks for bringing up the issue!

**Comment by larsbutler** [comment]
I hate to be a bother, but is there any progress on this? FWIW, probably a good default license would be Apache 2.0 (for most things OpenStack-related).

Thanks! =)

**Comment by clayg** [comment]
yeah ok stuck apache 2.0 in there, sorry for the delay!

**Comment by larsbutler** [comment]
Thanks @clayg! :)
