### ISSUE TITLE
AttributeError: 'VersionInfo' object has no attribute 'semantic_version'

### ISSUE THREAD

**Issue by klrmn** [swiftstack/vagrant-swift-all-in-one#19]
https://gist.github.com/klrmn/850bfcc6fe8ac21f2954
https://stackoverflow.com/questions/30159923/attributeerror-versioninfo-object-has-no-attribute-semantic-version

fixed by running
sudo pip install --upgrade testtools
before running vagrant provision again

**Comment by clayg** [comment]
fixed in 228022
