### ISSUE TITLE
Add extra VM?

### ISSUE THREAD

**Issue by psachin** [swiftstack/vagrant-swift-all-in-one#37]
How can I add extra VM with additional node? I see Env variable EXTRA_VMS=0 in `localrc`. Increasing the count is sufficient?

**Comment by clayg** [comment]
Yeah it looks like that should still work - but I never really liked how that experiment turned out.  I was planning on ripping it out.

So, if you manage to find some use-case that option actually solves - I'd be interested to hear about it.
