### ISSUE TITLE
chef fails on recent vagrant versions

### ISSUE THREAD

**Issue by cschwede** [swiftstack/vagrant-swift-all-in-one#38]
Related: https://github.com/chef/chef/issues/4948

Simplest fix is to add chef.version = "12.10.40":

```
diff --git a/Vagrantfile b/Vagrantfile
index 262c605..80b5330 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -90,6 +90,7 @@ Vagrant.configure("2") do |global_config|
         end
       end
       config.vm.provision :chef_solo do |chef|
+        chef.version = "12.10.40"
         chef.add_recipe "swift"
         chef.json = local_config
       end
```

**Comment by clayg** [comment]
I can't follow the referenced bug on the chef project - it's closed?  There's also a vagrant bug which adds a `--legacy-mode` option that is also merged?  I'm not sure what the suggested path forward is?  I'm unsure about pining the chef version?  I'll try to upgrade vagrant and chef to the latest versions and see if this will build - do you have a traceback from when this bug hits?

**Comment by cschwede** [comment]
Clay, here is a fresh traceback: [vagrant-chef-error.txt](https://github.com/swiftstack/vagrant-swift-all-in-one/files/281033/vagrant-chef-error.txt)
Happens on vagrant 1.8.1 (current latest) on OSX with an unmodified Vagrantfile.
I don't like version pining as well, but this info might be helpful to others for the time being?

**Comment by tipabu** [comment]
FYI, `12.10.40` 404s now.

That thread seemed to indicate that setting `chef.channel = "stable"` should help, but that still produced the same 404-from-`chefzero://localhost:8889` behavior. (FWIW, stable currently pulls in `12.11.18`.) Ditto for setting the version to just `12.10` (and getting `12.10.60`).

Trying to get `12.9` 404s. Ditto for `11`.

Looking for a solution, but it's tricky; I have no idea how to get version numbers to try.

**Comment by tipabu** [comment]
Ok, looks like adding

    chef.channel = "stable"
    chef.version = "12.10"

... will pull in `12.10.24`, which actually works. (For now.)

**Comment by craigfurman** [comment]
Does this look like a vagrant / chef bug, or is pinning the version something that is encouraged for the chef solo provisioner?

**Comment by clayg** [comment]
Seems to womm after upgrading to vagrant `1.8.4`: https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#183-june-10-2016

... strangely I tried *just* setting the channel to `stable` (without pinning to `12.10`) and chef `12.11.XX` which was the latest did not work for me on vagrant `1.8.1.1`?
