### ISSUE TITLE
Use "real" disks

### ISSUE THREAD

**Issue by clayg** [swiftstack/vagrant-swift-all-in-one#43]
Mostly the changes should be to the data recipe [1]

I have some code in another context that does this:

```
@fab.roles('node')
@fab.parallel
def _clean_devices():
    for i in range(DEVICE_COUNT):
        fab.run('dmsetup remove dev%s || true' % i)
        fab.run('losetup -d /dev/loop%s || true' % i)
        fab.run('rm /var/dev%s.block || true' % i)
    fab.run('udevadm settle')


@fab.roles('node')
@fab.parallel
def _create_devices():
    for i in range(DEVICE_COUNT):
        fab.run('dd if=/dev/zero of=/var/dev%s.block bs=1M count=3000' % i)
    for i in range(DEVICE_COUNT):
        fab.run('losetup /dev/loop{0} /var/dev{0}.block'.format(i))
    for i in range(DEVICE_COUNT):
        sectors = fab.run('blockdev --getsize /dev/loop%s' % i)
        fab.run('dmsetup create dev{0} --table '
                '"0 {1} linear /dev/loop{0} 0"'.format(i, sectors))

@fab.task
@fab.runs_once
def setup_devices():
    """
    Add Device Mapper block devices to Nodes
    """
    fab.execute(_clean_devices)
    fab.execute(_create_devices)
```

... but I think that strategy could be improved further because vsaio's can potentially want many more swift devices than `/dev/loop*` entries ... 

I might just create a single _sparse_ file and loopback that onto `/dev/loop0` (like the recipe already does), but then break that up into `<sectors> / <DEVICE_COUNT>` "chunks" and then use `dmsetup` to create `dev<N>` device tables like `0 <chunks> linear /dev/loop0 <N * chunks>` [2]
1. https://github.com/swiftstack/vagrant-swift-all-in-one/blob/master/cookbooks/swift/recipes/data.rb
2. probably need to double check that, I think the syntax is `<start-of-table-entry> <size-of-table-entry> linear <source-device> <source-device-offset>` - since we only create one table entry per device, and always use the same loop device - I think it's always `0 <size-of-each-dev-in-sectors> linear /dev/loop0 <start-sector-offset-of-loop-device>` - https://www.kernel.org/doc/Documentation/device-mapper/linear.txt

**Comment by tipabu** [comment]
Closed by https://github.com/swiftstack/vagrant-swift-all-in-one/pull/77
