### ISSUE TITLE
Install pyeclib from source

### ISSUE THREAD

**Issue by clayg** [swiftstack/vagrant-swift-all-in-one#45]
I'm still getting these on my vsaio:

Aug 11 01:45:23 saio liberasurecode[4476]: liberasurecode_backend_open: dynamic linking error libJerasure.so.2: cannot open shared object file: No such file or directory
Aug 11 01:45:23 saio liberasurecode[4476]: liberasurecode_backend_open: dynamic linking error libJerasure.so.2: cannot open shared object file: No such file or directory
Aug 11 01:45:23 saio liberasurecode[4476]: liberasurecode_backend_open: dynamic linking error libisal.so.2: cannot open shared object file: No such file or directory
Aug 11 01:45:23 saio liberasurecode[4476]: liberasurecode_backend_open: dynamic linking error libshss.so.1: cannot open shared object file: No such file or directory
Aug 11 01:45:23 saio liberasurecode[4477]: liberasurecode_backend_open: dynamic linking error libJerasure.so.2: cannot open shared object file: No such file or directory
Aug 11 01:45:23 saio liberasurecode[4477]: liberasurecode_backend_open: dynamic linking error libJerasure.so.2: cannot open shared object file: No such file or directory
Aug 11 01:45:23 saio liberasurecode[4477]: liberasurecode_backend_open: dynamic linking error libisal.so.2: cannot open shared object file: No such file or directory
Aug 11 01:45:23 saio liberasurecode[4477]: liberasurecode_backend_open: dynamic linking error libshss.so.1: cannot open shared object file: No such file or directory

So lame.  I'm also scared to review https://review.openstack.org/#/c/344066/ because I don't know how to build/test the damn thing in my development environment :'(

**Comment by clayg** [comment]
fixed in 54334b

**Comment by nay122** [comment]
Hi! Nice to meet you.
I have the same errors with you and I found some related bugs about it but I could not find the solution. Could you share the info of 54224b? Is there any link here?

JFYI:
shared object file: No such file or directory
https://access.redhat.com/solutions/3012541
Bug 1440326
https://bugzilla.redhat.com/show_bug.cgi?id=1440326
Bug 1636541
https://bugzilla.redhat.com/show_bug.cgi?id=1636541
