### ISSUE TITLE
vagrant up results in a password prompt

### ISSUE THREAD

**Issue by timuralp** [swiftstack/vagrant-swift-all-in-one#52]
I pulled from master (7166a72e5667f8d6240ab17747c71514aa952162) and attempted to run `vagrant up`. The result was:
```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: timur
    default: SSH auth method: password
    default: Warning: Remote connection disconnect. Retrying...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
timur@127.0.0.1's password:    default: Warning: Connection timeout. Retrying...
```

I don't know why we would expect my username to work here? This line in the Vagrantfile is not clear to me:
```
31 username = (ENV['USERNAME'] || "ubuntu")
```

**Comment by clayg** [comment]
the default username of the new default xenial base box is ubuntu - if you did not recreate your current instance you need to update your localrc/environment to specifiy the username of `vagrant`

same thing bit @tipabu - the note in the localrc-template [1] is not sufficiently descriptive of the situation - but ultimately this is working as expected

1. https://github.com/swiftstack/vagrant-swift-all-in-one/blob/7166a72e5667f8d6240ab17747c71514aa952162/localrc-template#L2

**Comment by clayg** [comment]
the default configuration without a localrc was picking up the USERNAME from the linux environment - selecting a better configuration environment variable name should work around the bad ergonomics here pr #53
