### ISSUE TITLE
container sharding (feature/deep branch) requires internal-client.conf

### ISSUE THREAD

**Issue by notmyname** [swiftstack/vagrant-swift-all-in-one#68]
The sample from the master branch is sufficient.

**Comment by clayg** [comment]
So, my vsaio has `/etc/swift/internal-client.conf` and I think master already supports/sets-up container sharding [1].  I don't think there's anything more to do here, but feel free to set me straight and reopen!

1. https://github.com/swiftstack/vagrant-swift-all-in-one/blob/master/cookbooks/swift/templates/default/etc/swift/container-server/settings.conf.erb#L8
